name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y oathtool

      - name: Configure credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          echo -e ":rubygems_api_key: ${GEM_HOST_API_KEY}" > $HOME/.gem/credentials
          echo -e ":github: ${RUBYGEMS_API_KEY}" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

      - name: Build gem
        run: |
          gem build *.gemspec

      - name: Generate OTP
        id: generate_otp
        run: |
          otp_code=$(oathtool --totp -b ${{ secrets.MFA_SHARED_SECRET }})
          echo "::set-output name=otp::$otp_code"

      - name: Publish to GPR & RubyGems
        run: |
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
          gem push *.gem --host https://rubygems.org --otp ${{ steps.generate_otp.outputs.otp }}
        env:
          OWNER: ${{ github.repository_owner }}
